(function(){var GBS_HOST = "https://www.google.com/";/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h=this||self;function k(a,b){a=a.split(".");var c=h;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b}function m(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function p(a){return a};var q=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&b.call(void 0,e[g],g,a)};function r(a){var b=a.length;if(0<b){for(var c=Array(b),e=0;e<b;e++)c[e]=a[e];return c}return[]};var t=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},u=/&/g,v=/</g,w=/>/g,x=/"/g,y=/'/g,z=/\x00/g,aa=/[\x00&<>"']/;function A(a,b){return a<b?-1:a>b?1:0};var B;a:{var C=h.navigator;if(C){var D=C.userAgent;if(D){B=D;break a}}B=""};function ba(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var E="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ca(a,b){for(var c,e,g=1;g<arguments.length;g++){e=arguments[g];for(c in e)a[c]=e[c];for(var d=0;d<E.length;d++)c=E[d],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};var F;function G(a,b){this.g=b===H?a:""}G.prototype.j=!0;G.prototype.i=function(){return this.g.toString()};G.prototype.toString=function(){return this.g.toString()};
var da=/^(?:audio\/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font\/\w+|image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video\/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\w+=(?:\w+|"[\w;,= ]+"))*$/i,ea=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,fa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,H={},ha=new G("about:invalid#zClosurez",H);function I(a,b,c){this.g=c===J?a:""}I.prototype.j=!0;I.prototype.i=function(){return this.g.toString()};I.prototype.toString=function(){return this.g.toString()};var J={};function K(a){aa.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(u,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(v,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(w,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(x,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(y,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(z,"&#0;")));return a};function ia(a){var b=ja;return Object.prototype.hasOwnProperty.call(b,"10")?b["10"]:b["10"]=a("10")};var ka=-1!=B.indexOf("Opera"),L=-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"),la=-1!=B.indexOf("Edge"),ma=-1!=B.indexOf("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"))&&!(-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"))&&-1==B.indexOf("Edge"),na=-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge");function M(){var a=h.document;return a?a.documentMode:void 0}var N;
a:{var O="",P=function(){var a=B;if(ma)return/rv:([^\);]+)(\)|;)/.exec(a);if(la)return/Edge\/([\d\.]+)/.exec(a);if(L)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(na)return/WebKit\/(\S+)/.exec(a);if(ka)return/(?:Version)[ \/]?(\S+)/.exec(a)}();P&&(O=P?P[1]:"");if(L){var Q=M();if(null!=Q&&Q>parseFloat(O)){N=String(Q);break a}}N=O}var R=N,ja={};
function oa(){return ia(function(){for(var a=0,b=t(String(R)).split("."),c=t("10").split("."),e=Math.max(b.length,c.length),g=0;0==a&&g<e;g++){var d=b[g]||"",f=c[g]||"";do{d=/(\d*)(\D*)(.*)/.exec(d)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(0==d[0].length&&0==f[0].length)break;a=A(0==d[1].length?0:parseInt(d[1],10),0==f[1].length?0:parseInt(f[1],10))||A(0==d[2].length,0==f[2].length)||A(d[2],f[2]);d=d[3];f=f[3]}while(0==a)}return 0<=a})}var S;
if(h.document&&L){var T=M();S=T?T:parseInt(R,10)||void 0}else S=void 0;var pa=S;var U;(U=!L)||(U=9<=Number(pa));var qa=U;function ra(a,b){ba(b,function(c,e){c&&"object"==typeof c&&c.j&&(c=c.i());"style"==e?a.style.cssText=c:"class"==e?a.className=c:"for"==e?a.htmlFor=c:V.hasOwnProperty(e)?a.setAttribute(V[e],c):0==e.lastIndexOf("aria-",0)||0==e.lastIndexOf("data-",0)?a.setAttribute(e,c):a[e]=c})}
var V={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function sa(a,b,c){var e=arguments,g=document,d=String(e[0]),f=e[1];if(!qa&&f&&(f.name||f.type)){d=["<",d];f.name&&d.push(' name="',K(f.name),'"');if(f.type){d.push(' type="',K(f.type),'"');var l={};ca(l,f);delete l.type;f=l}d.push(">");d=d.join("")}d=String(d);"application/xhtml+xml"===g.contentType&&(d=d.toLowerCase());d=g.createElement(d);f&&("string"===typeof f?d.className=f:Array.isArray(f)?d.className=f.join(" "):ra(d,f));2<e.length&&ta(g,d,e);return d}
function ta(a,b,c){function e(l){l&&b.appendChild("string"===typeof l?a.createTextNode(l):l)}for(var g=2;g<c.length;g++){var d=c[g];if(!m(d)||n(d)&&0<d.nodeType)e(d);else{a:{if(d&&"number"==typeof d.length){if(n(d)){var f="function"==typeof d.item||"string"==typeof d.item;break a}if("function"===typeof d){f="function"==typeof d.item;break a}}f=!1}q(f?r(d):d,e)}}};var W=[],X=!1,Y=!1;k("google.books.load",function(a){a&&null!=a.callback?("string"==typeof a.callback&&a.callback.match(/^[[\]A-Za-z0-9._]+$/)&&(a.callback=window.eval(a.callback)),(a&&null!=a.callback?Y:X)?window.setTimeout(a.callback,0):(W.push(a.callback),Z(a))):(a&&null!=a.callback?Y:X)||(X=!0,Z(a))});
k("google.books.setOnLoadCallback",function(a){if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a);else{var b=window.onload;window.onload=null!=b?function(){a();b()}:a}});k("google.books.handleLoadCallback",function(){Y=!0;for(var a=0;a<W.length;a++)window.setTimeout(W[a],0);W=[]});
function Z(a){var b="";if(a){if(a.language){var c=a.language;if("string"==typeof c||c instanceof String)c=c.replace(/\s/g,""),b+="&hl="+encodeURIComponent(String(c))}a.callback&&(b+="&callback=google.books.handleLoadCallback")}b&&(b="?"+b.substring(1));a="https://www.google.com/books/api.js"+b;a instanceof G||(a="object"==typeof a&&a.j?a.i():String(a),fa.test(a)?a=new G(a,H):(a=String(a),a=a.replace(/(%0A|%0D)/g,""),a=(b=a.match(ea))&&da.test(b[1])?new G(a,H):null));a=a||ha;a=a instanceof G&&a.constructor===
G?a.g:"type_error:SafeUrl";if(L&&!oa()){a='<script src="'+a+'">\x3c/script>';if(void 0===F)if(b=null,(c=h.trustedTypes)&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:p,createScript:p,createScriptURL:p})}catch(e){h.console&&h.console.error(e.message)}F=b}else F=b;a=(b=F)?b.createHTML(a):a;a=new I(a,null,J);document.write(a instanceof I&&a.constructor===I?a.g:"type_error:SafeHtml")}else a=sa("SCRIPT",{src:a}),document.getElementsByTagName("head")[0].appendChild(a);X=!0};
})();